Formatted attachment for email notification service
ProyectoIntegrador2018/oportunidades pull request #86
Opened 2021-04-14 19:04 UTC by MarthaArnaud

Mejora del formato del pdf generado, modificando la estructura y agregando estilos al HTML.
Screenshot del pdf:
![IMG_9491](https://user-images.githubusercontent.com/35774986/114764692-de13ed80-9d29-11eb-8a25-f778bea7ffff.PNG)
Screenshot de todo el mail recibido, que trae el archivo adjunto:
[Nueva Oportunidad Comercial.pdf](https://github.com/ProyectoIntegrador2018/oportunidades/files/6313112/Nueva.Oportunidad.Comercial.pdf)

2021-04-14 22:54 UTC, ariel-ms approved these changes

2021-04-16 05:37 UTC, raulherreras requested changes
Se ve bien! Solo dejé algunos comentarios

2021-04-16 05:37 UTC, raulherreras commented on server/services/MailService.js
>          content: mailContent.attachments.content,
Creo que sería mejor sólo agregar el texto de Nueva Oportunidad y el attachment del PDF, solo en el caso de que el tipo de notificación sea Nueva Oportunidad, ya que como está ahorita, se agregaría esto aun para los correos de otros tipos de notificaciones. Tal vez podrías checar el inicio de `mailContent.html` o pasar como parámetro el `notificationType` y así determinar si es de Nueva Oportunidad o no.

2021-04-16 05:37 UTC, raulherreras commented on server/services/MailService.js
> +Notificaciones de CSOFTMTY`;
El párrafo de despedida se agrega para todos los tipos de notificaciones en la línea 157.

2021-04-16 23:02 UTC, ArthArenas approved these changes
El formato de ahora se ve muy bien!

2021-04-19 02:51 UTC, MarthaArnaud commented on server/services/MailService.js
>          content: mailContent.attachments.content,
Muchas gracias Raúl ya lo corregí!

2021-04-19 02:52 UTC, MarthaArnaud commented on server/services/MailService.js
> +Notificaciones de CSOFTMTY`;
Listo también!

2021-04-19 03:17 UTC, raulherreras approved these changes

2021-04-19 05:11 UTC, merged